language: java
jdk:
  - oraclejdk7

notifications:
  email:
    - fkorotkov@twitter.com

install: ./scripts/setup-ci-environment.sh

env:
  global:
    - OSS_PANTS_HOME=./.cache/intellij/pants
  matrix:
    - IJ_VERSION="14.0.3" IJ_BUILD_NUMBER="139.1117" USE_PANTS_TO_COMPILE=false
    - IJ_VERSION="14.0.3" IJ_BUILD_NUMBER="139.1117" IJ_ULTIMATE=true
    - IJ_VERSION="14.0.3" IJ_BUILD_NUMBER="139.1117"
    - IJ_VERSION="14.0.3" IJ_BUILD_NUMBER="139.1117" USE_ISOLATED_STRATEGY=true

script:
  - ./scripts/run-tests-ci.sh
  - ./scripts/run-custom-integration.sh
      -r $OSS_PANTS_HOME
      -t examples/src/scala/org/pantsbuild/example/hello,examples/src/java/org/pantsbuild/example/hello
